# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8878fe9edeeda84dc5f422e93a298dc82513420c529b5bcd5c04393da16afb7aebf9eee45df86f17feb3bb014802fe20e67143846fe5999bcdb838994b819643

test:
  secret_key_base: 37b4104f81f9daf54ad135ee9c6eadd8272113b7b9aa007c2b42e84712beaf00cfa11bcca3fd09fe4cf209f12692e2819651e6a80bf77edb6365fda051d95cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
